# Shared helpers for the script-mode entry points (cmake -P scripts/<task>.cmake).
# Everything portable lives here; scripts/<os>/ only holds what is truly OS-specific.

cmake_minimum_required(VERSION 3.28)

get_filename_component(EZ_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(EZ_MANIFEST "${EZ_ROOT}/dependencies.json")
set(EZ_SRC_ROOT "${EZ_ROOT}/third_party/_src")
set(EZ_STAMP_DIR "${EZ_SRC_ROOT}/.stamps")

# ---------------------------------------------------------------- host
function(ez_host out)
  cmake_host_system_information(RESULT _arch QUERY OS_PLATFORM)
  string(TOLOWER "${_arch}" _arch)
  if(_arch MATCHES "amd64|x86_64|x64")
    set(_arch "x86_64")
  elseif(_arch MATCHES "arm64|aarch64")
    set(_arch "arm64")
  endif()
  if(CMAKE_HOST_WIN32)
    set(_os "windows")
  elseif(CMAKE_HOST_APPLE)
    set(_os "macos")
  else()
    set(_os "linux")
  endif()
  set(${out} "${_os}-${_arch}" PARENT_SCOPE)
endfunction()

ez_host(EZ_HOST)
string(REGEX REPLACE "-.*" "" EZ_HOST_OS "${EZ_HOST}")

# ---------------------------------------------------------------- arguments
# cmake -P scripts/x.cmake --foo=bar --flag  ->  EZ_ARG_foo=bar, EZ_ARG_flag=ON
function(ez_parse_args)
  set(_after_script OFF)
  math(EXPR _last "${CMAKE_ARGC} - 1")
  foreach(i RANGE 0 ${_last})
    set(_a "${CMAKE_ARGV${i}}")
    if(_after_script)
      if(_a MATCHES "^--([A-Za-z0-9_-]+)=(.*)$")
        string(REPLACE "-" "_" _k "${CMAKE_MATCH_1}")
        set(EZ_ARG_${_k} "${CMAKE_MATCH_2}" PARENT_SCOPE)
      elseif(_a MATCHES "^--([A-Za-z0-9_-]+)$")
        string(REPLACE "-" "_" _k "${CMAKE_MATCH_1}")
        set(EZ_ARG_${_k} ON PARENT_SCOPE)
      elseif(NOT _a STREQUAL "--")
        list(APPEND _pos "${_a}")
      endif()
    elseif(_a STREQUAL "-P")
      math(EXPR _next "${i} + 1")
      set(_skip_index ${_next})
    elseif(DEFINED _skip_index AND i EQUAL _skip_index)
      set(_after_script ON)
    endif()
  endforeach()
  set(EZ_ARGS_POSITIONAL "${_pos}" PARENT_SCOPE)
endfunction()

# ---------------------------------------------------------------- output
if(NOT CMAKE_HOST_WIN32 OR DEFINED ENV{WT_SESSION})
  string(ASCII 27 _esc)
  set(EZ_C_RED "${_esc}[31m")
  set(EZ_C_GREEN "${_esc}[32m")
  set(EZ_C_YELLOW "${_esc}[33m")
  set(EZ_C_DIM "${_esc}[2m")
  set(EZ_C_BOLD "${_esc}[1m")
  set(EZ_C_RESET "${_esc}[0m")
endif()

function(ez_say msg)
  message("${msg}")
endfunction()

function(ez_step msg)
  message("${EZ_C_BOLD}==> ${msg}${EZ_C_RESET}")
endfunction()

# ez_report(OK|WARN|ERROR <name> <detail> [<fix>])
# Accumulates EZ_REPORT_ERRORS / EZ_REPORT_WARNINGS in the caller's scope.
macro(ez_report level name detail)
  set(_fix "${ARGN}")
  if("${level}" STREQUAL "OK")
    message("  ${EZ_C_GREEN}ok   ${EZ_C_RESET} ${name}  ${EZ_C_DIM}${detail}${EZ_C_RESET}")
  elseif("${level}" STREQUAL "WARN")
    math(EXPR EZ_REPORT_WARNINGS "${EZ_REPORT_WARNINGS} + 0 + 1")
    message("  ${EZ_C_YELLOW}warn ${EZ_C_RESET} ${name}  ${detail}")
  else()
    math(EXPR EZ_REPORT_ERRORS "${EZ_REPORT_ERRORS} + 0 + 1")
    message("  ${EZ_C_RED}error${EZ_C_RESET} ${name}  ${detail}")
  endif()
  if(NOT "${_fix}" STREQUAL "")
    message("         ${EZ_C_DIM}fix:${EZ_C_RESET} ${_fix}")
  endif()
endmacro()

# ---------------------------------------------------------------- manifest
file(READ "${EZ_MANIFEST}" EZ_MANIFEST_JSON)

function(ez_manifest_names out)
  string(JSON _n LENGTH "${EZ_MANIFEST_JSON}" dependencies)
  set(_names "")
  if(_n GREATER 0)
    math(EXPR _last "${_n} - 1")
    foreach(i RANGE 0 ${_last})
      string(JSON _name GET "${EZ_MANIFEST_JSON}" dependencies ${i} name)
      list(APPEND _names "${_name}")
    endforeach()
  endif()
  set(${out} "${_names}" PARENT_SCOPE)
endfunction()

function(ez_manifest_index name out)
  string(JSON _n LENGTH "${EZ_MANIFEST_JSON}" dependencies)
  math(EXPR _last "${_n} - 1")
  foreach(i RANGE 0 ${_last})
    string(JSON _name GET "${EZ_MANIFEST_JSON}" dependencies ${i} name)
    if(_name STREQUAL name)
      set(${out} ${i} PARENT_SCOPE)
      return()
    endif()
  endforeach()
  message(FATAL_ERROR "dependency '${name}' is not in dependencies.json")
endfunction()

# ez_manifest_get(<name> <out> <key> [<key>...]); <out> is empty if the key is missing
function(ez_manifest_get name out)
  ez_manifest_index(${name} _i)
  string(JSON _v ERROR_VARIABLE _err GET "${EZ_MANIFEST_JSON}" dependencies ${_i} ${ARGN})
  if(_err)
    set(_v "")
  endif()
  set(${out} "${_v}" PARENT_SCOPE)
endfunction()

function(ez_manifest_used_by name out)
  ez_manifest_index(${name} _i)
  string(JSON _n LENGTH "${EZ_MANIFEST_JSON}" dependencies ${_i} used_by)
  set(_l "")
  if(_n GREATER 0)
    math(EXPR _last "${_n} - 1")
    foreach(j RANGE 0 ${_last})
      string(JSON _u GET "${EZ_MANIFEST_JSON}" dependencies ${_i} used_by ${j})
      list(APPEND _l "${_u}")
    endforeach()
  endif()
  set(${out} "${_l}" PARENT_SCOPE)
endfunction()

# ---------------------------------------------------------------- per-user locations
# Tools are installed per user, keyed by version (B-14). Override with EZ_TOOLS_DIR.
function(ez_user_cache_root out)
  if(DEFINED ENV{EZ_CACHE_DIR})
    set(_r "$ENV{EZ_CACHE_DIR}")
  elseif(CMAKE_HOST_WIN32)
    set(_r "$ENV{LOCALAPPDATA}/ezego")
  elseif(CMAKE_HOST_APPLE)
    set(_r "$ENV{HOME}/Library/Caches/ezego")
  elseif(DEFINED ENV{XDG_CACHE_HOME})
    set(_r "$ENV{XDG_CACHE_HOME}/ezego")
  else()
    set(_r "$ENV{HOME}/.cache/ezego")
  endif()
  file(TO_CMAKE_PATH "${_r}" _r)
  set(${out} "${_r}" PARENT_SCOPE)
endfunction()

function(ez_tools_root out)
  if(DEFINED ENV{EZ_TOOLS_DIR})
    file(TO_CMAKE_PATH "$ENV{EZ_TOOLS_DIR}" _r)
  else()
    ez_user_cache_root(_c)
    set(_r "${_c}/tools")
  endif()
  set(${out} "${_r}" PARENT_SCOPE)
endfunction()

# ---------------------------------------------------------------- programs
function(ez_require_git out)
  find_program(_git NAMES git)
  if(NOT _git)
    message(FATAL_ERROR "git was not found on PATH. Run: cmake -P scripts/doctor.cmake")
  endif()
  set(${out} "${_git}" PARENT_SCOPE)
endfunction()

# Run a command, fail loudly with its output.
function(ez_run)
  cmake_parse_arguments(R "QUIET;ALLOW_FAIL" "WORKING_DIRECTORY;RESULT;OUTPUT" "COMMAND" ${ARGN})
  if(NOT R_WORKING_DIRECTORY)
    set(R_WORKING_DIRECTORY "${EZ_ROOT}")
  endif()
  execute_process(COMMAND ${R_COMMAND}
    WORKING_DIRECTORY "${R_WORKING_DIRECTORY}"
    RESULT_VARIABLE _rc OUTPUT_VARIABLE _out ERROR_VARIABLE _out
    OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(R_RESULT)
    set(${R_RESULT} ${_rc} PARENT_SCOPE)
  endif()
  if(R_OUTPUT)
    set(${R_OUTPUT} "${_out}" PARENT_SCOPE)
  endif()
  if(NOT _rc EQUAL 0 AND NOT R_ALLOW_FAIL)
    list(JOIN R_COMMAND " " _cmd)
    message(FATAL_ERROR "command failed (${_rc}): ${_cmd}\n${_out}")
  endif()
endfunction()

# The cmake binary running this script, for sub-invocations.
set(EZ_CMAKE "${CMAKE_COMMAND}")
