# Health check (B-6). Read-only: it never installs anything; every failed check prints the
# exact fix for this OS. Exit code 1 if any ERROR.
#
#   cmake -P scripts/doctor.cmake
#
# Portable checks live here; OS-specific ones in scripts/<os>/doctor.(sh|ps1), which print
# "LEVEL|name|detail|fix" lines that are folded into the same report.

include("${CMAKE_CURRENT_LIST_DIR}/lib/common.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/lib/tooling.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/lib/llvm.cmake")
ez_parse_args()
set(EZ_REPORT_ERRORS 0)
set(EZ_REPORT_WARNINGS 0)

# ------------------------------------------------------------------ OS-specific findings
if(EZ_HOST_OS STREQUAL "windows")
  execute_process(COMMAND powershell -NoProfile -ExecutionPolicy Bypass -File "${EZ_ROOT}/scripts/windows/doctor.ps1"
    OUTPUT_VARIABLE _os_out ERROR_VARIABLE _os_err)
else()
  execute_process(COMMAND sh "${EZ_ROOT}/scripts/${EZ_HOST_OS}/doctor.sh" OUTPUT_VARIABLE _os_out ERROR_VARIABLE _os_err)
endif()
string(REPLACE "\r" "" _os_out "${_os_out}")
string(REPLACE ";" "," _os_out "${_os_out}")
string(REPLACE "\n" ";" _os_lines "${_os_out}")
set(_os_findings "")
foreach(_l IN LISTS _os_lines)
  if(_l MATCHES "^HINT\\|([^|]*)\\|([^|]*)")
    set(EZ_HINT_${CMAKE_MATCH_1} "${CMAKE_MATCH_2}")
  elseif(_l MATCHES "^(OK|WARN|ERROR)\\|")
    list(APPEND _os_findings "${_l}")
  endif()
endforeach()

macro(ez_os_report_all)
  foreach(_f IN LISTS _os_findings)
    string(REPLACE "|" ";" _p "${_f}")
    list(LENGTH _p _n)
    list(GET _p 0 _lvl)
    list(GET _p 1 _name)
    list(GET _p 2 _detail)
    set(_fix "")
    if(_n GREATER 3)
      list(GET _p 3 _fix)
    endif()
    ez_report(${_lvl} "${_name}" "${_detail}" "${_fix}")
  endforeach()
endmacro()

# ------------------------------------------------------------------ core tools
ez_step("Toolchain (${EZ_HOST})")
if(CMAKE_VERSION VERSION_LESS 3.28)
  ez_report(ERROR "cmake" "${CMAKE_VERSION}, need >= 3.28" "${EZ_HINT_toolchain}")
else()
  ez_report(OK "cmake" "${CMAKE_VERSION}  ${CMAKE_COMMAND}")
endif()

find_program(_ninja ninja NO_CACHE)
if(_ninja)
  execute_process(COMMAND "${_ninja}" --version OUTPUT_VARIABLE _v OUTPUT_STRIP_TRAILING_WHITESPACE)
  ez_report(OK "ninja" "${_v}  ${_ninja}")
else()
  ez_report(ERROR "ninja" "not found" "${EZ_HINT_toolchain}")
endif()

find_program(_git git NO_CACHE)
if(_git)
  execute_process(COMMAND "${_git}" --version OUTPUT_VARIABLE _v OUTPUT_STRIP_TRAILING_WHITESPACE)
  ez_report(OK "git" "${_v}")
else()
  ez_report(ERROR "git" "not found (dependencies are fetched with git)" "install git")
endif()

# Compiler: the same search order as cmake/toolchain.cmake
set(_min_clang 17)
if(EZ_HOST_OS STREQUAL "windows")
  find_program(_cc NAMES clang-cl NO_CACHE HINTS "$ENV{ProgramFiles}/LLVM/bin")
elseif(EZ_HOST_OS STREQUAL "macos")
  find_program(_cc NAMES clang NO_CACHE)
else()
  find_program(_cc NAMES clang clang-22 clang-21 clang-20 clang-19 clang-18 clang-17 NO_CACHE)
endif()
if(_cc)
  execute_process(COMMAND "${_cc}" --version OUTPUT_VARIABLE _v)
  string(REGEX MATCH "version ([0-9]+)\\.[0-9.]+" _m "${_v}")
  set(_major "${CMAKE_MATCH_1}")
  string(REGEX MATCH "^[^\n]*" _first "${_v}")
  if(EZ_HOST_OS STREQUAL "macos" OR _major GREATER_EQUAL _min_clang)
    ez_report(OK "clang" "${_first}")
  else()
    ez_report(ERROR "clang" "${_first}: need >= ${_min_clang}" "${EZ_HINT_toolchain}")
  endif()
else()
  ez_report(ERROR "clang" "not found (eZeGo builds with Clang on every OS)" "${EZ_HINT_toolchain}")
endif()

if(EZ_HOST_OS STREQUAL "linux")
  find_program(_mold mold NO_CACHE)
  find_program(_lld NAMES ld.lld ld.lld-19 ld.lld-18 NO_CACHE)
  if(_mold)
    ez_report(OK "linker" "mold ${_mold}")
  elseif(_lld)
    ez_report(WARN "linker" "lld only; mold links faster" "${EZ_HINT_accelerators}")
  else()
    ez_report(WARN "linker" "neither mold nor lld; using the slow default linker" "${EZ_HINT_accelerators}")
  endif()
endif()

find_program(_cache NAMES sccache ccache NO_CACHE)
set(_cache_ok OFF)
if(_cache)
  execute_process(COMMAND "${_cache}" --version RESULT_VARIABLE _rc OUTPUT_QUIET ERROR_QUIET)
  if(_rc EQUAL 0)
    set(_cache_ok ON)
  endif()
endif()
if(_cache_ok)
  ez_report(OK "compiler cache" "${_cache}")
else()
  ez_report(WARN "compiler cache" "none; rebuilds and branch switches will be slower" "${EZ_HINT_accelerators}")
endif()

# LLVM tools (naming.md N-13): same major version as the compiler, because versions disagree on
# formatting and lint edge cases. Apple Clang's numbering differs from LLVM's, so macOS only checks
# presence. Overrides: EZ_CLANGD, EZ_CLANG_FORMAT, EZ_CLANG_TIDY environment variables.
string(REPLACE "@MAJOR@" "${_major}" EZ_HINT_clang_tools "${EZ_HINT_clang_tools}")
string(REPLACE "@MAJOR@" "${_major}" EZ_HINT_clang_tidy "${EZ_HINT_clang_tidy}")
foreach(_t clangd clang-format clang-tidy)
  if(_t STREQUAL "clang-tidy")
    set(_why "needed by ez lint and ez check: naming rules")
    set(_hint "${EZ_HINT_clang_tidy}")
  elseif(_t STREQUAL "clang-format")
    set(_why "needed by ez lint and ez check: formatting")
    set(_hint "${EZ_HINT_clang_tools}")
  else()
    set(_why "editor support")
    set(_hint "${EZ_HINT_clang_tools}")
  endif()
  set(_cmajor "${_major}")
  if(EZ_HOST_OS STREQUAL "macos")
    set(_cmajor "")
  endif()
  ez_find_llvm_tool(${_t} _p _pm COMPILER_MAJOR "${_cmajor}")
  if(NOT _p)
    ez_report(WARN "${_t}" "not found (${_why})" "${_hint}")
  elseif(_cmajor AND NOT _pm STREQUAL _cmajor)
    ez_report(WARN "${_t}" "version ${_pm} at ${_p}, compiler is ${_cmajor}; results may differ from other machines" "${_hint}")
  else()
    ez_report(OK "${_t}" "${_pm}  ${_p}")
  endif()
endforeach()

ez_step("System (${EZ_HOST_OS})")
ez_os_report_all()

# init asks for a system-only check: on a fresh clone nothing is fetched yet.
if(NOT EZ_DOCTOR_SYSTEM_ONLY)
# ------------------------------------------------------------------ repository state
ez_step("Repository")
if(EXISTS "${EZ_ROOT}/.gitmodules")
  ez_report(WARN "submodules" "a .gitmodules file exists; dependencies come from dependencies.json now" "git rm .gitmodules")
endif()
ez_manifest_names(_deps)
foreach(_d IN LISTS _deps)
  ez_manifest_get(${_d} _c commit)
  ez_manifest_get(${_d} _ver version)
  string(SUBSTRING "${_c}" 0 10 _s)
  set(_dir "${EZ_SRC_ROOT}/${_d}")
  if(NOT EXISTS "${_dir}/.git")
    ez_report(ERROR "dep ${_d}" "not fetched" "cmake -P scripts/deps.cmake")
    continue()
  endif()
  execute_process(COMMAND "${_git}" rev-parse HEAD WORKING_DIRECTORY "${_dir}" OUTPUT_VARIABLE _h OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process(COMMAND "${_git}" status --porcelain WORKING_DIRECTORY "${_dir}" OUTPUT_VARIABLE _st)
  file(GLOB _patches "${EZ_ROOT}/third_party/patches/${_d}/*.patch")
  if(NOT _h STREQUAL _c)
    ez_report(ERROR "dep ${_d}" "at ${_h}, manifest pins ${_s}" "cmake -P scripts/deps.cmake")
  elseif(NOT _st STREQUAL "" AND NOT _patches)
    ez_report(WARN "dep ${_d}" "${_ver} @ ${_s} has local modifications" "git -C third_party/_src/${_d} diff")
  else()
    ez_report(OK "dep ${_d}" "${_ver} @ ${_s}")
  endif()
endforeach()

ez_step("Dev tools")
file(GLOB _recipes "${EZ_ROOT}/tools/*.cmake")
foreach(_r IN LISTS _recipes)
  get_filename_component(_tool "${_r}" NAME_WE)
  ez_manifest_get(${_tool} _ver version)
  ez_tool_state(${_tool} _state _origin)
  ez_tool_install_dir(${_tool} _tdir)
  if(_state STREQUAL "OK")
    ez_report(OK "${_tool} ${_ver}" "${_origin}  ${_tdir}")
  elseif(_state STREQUAL "STALE")
    ez_report(WARN "${_tool} ${_ver}" "installed copy does not match the pin" "cmake -P scripts/tools.cmake --force")
  else()
    ez_report(WARN "${_tool} ${_ver}" "not installed (needed for profiling)" "cmake -P scripts/tools.cmake")
  endif()
endforeach()

ez_step("Build trees")
file(GLOB _trees LIST_DIRECTORIES true "${EZ_ROOT}/build/*")
set(_any_tree OFF)
foreach(_t IN LISTS _trees)
  if(NOT EXISTS "${_t}/CMakeCache.txt")
    continue()
  endif()
  set(_any_tree ON)
  get_filename_component(_name "${_t}" NAME)
  file(GLOB _cc_files "${_t}/CMakeFiles/*/CMakeCXXCompiler.cmake")
  set(_cxx "")
  if(_cc_files)
    list(GET _cc_files 0 _ccf)
    file(STRINGS "${_ccf}" _line REGEX "^set\\(CMAKE_CXX_COMPILER \"")
    string(REGEX REPLACE "^set\\(CMAKE_CXX_COMPILER \"([^\"]*)\".*" "\\1" _cxx "${_line}")
  endif()
  if(_cxx AND NOT EXISTS "${_cxx}")
    ez_report(WARN "build/${_name}" "configured with ${_cxx}, which no longer exists" "cmake -E rm -rf build/${_name}")
  else()
    ez_report(OK "build/${_name}" "${_cxx}")
  endif()
endforeach()
if(NOT _any_tree)
  ez_report(OK "build trees" "none yet")
endif()
if(EXISTS "${EZ_ROOT}/eZeGo.code-workspace")
  ez_report(OK "VS Code workspace" "eZeGo.code-workspace")
else()
  ez_report(WARN "VS Code workspace" "not generated" "cmake -P scripts/init.cmake   (or scripts/tools.cmake)")
endif()

endif()

# ------------------------------------------------------------------ summary
message("")
if(EZ_REPORT_ERRORS GREATER 0)
  message("${EZ_C_RED}${EZ_REPORT_ERRORS} error(s)${EZ_C_RESET}, ${EZ_REPORT_WARNINGS} warning(s). Fix the errors above, then re-run doctor.")
  message(FATAL_ERROR "doctor found ${EZ_REPORT_ERRORS} error(s)")
else()
  message("${EZ_C_GREEN}ready${EZ_C_RESET}: 0 errors, ${EZ_REPORT_WARNINGS} warning(s).")
endif()
