# Help for the `ez` launcher (build-system.md B-4). One source of text for every OS: the launchers
# call `cmake -P scripts/help.cmake [command]`.
#
#   cmake -P scripts/help.cmake            overview of every command
#   cmake -P scripts/help.cmake test       everything about one command
#
# Presets are read from CMakePresets.json through `cmake --list-presets`, so this never drifts
# from the real list.

include("${CMAKE_CURRENT_LIST_DIR}/lib/common.cmake")

set(_topic "")
math(EXPR _last "${CMAKE_ARGC} - 1")
set(_after OFF)
foreach(i RANGE 0 ${_last})
  set(_a "${CMAKE_ARGV${i}}")
  if(_after AND NOT _a MATCHES "^-")
    set(_topic "${_a}")
    break()
  elseif(_a STREQUAL "-P")
    math(EXPR _skip "${i} + 1")
  elseif(DEFINED _skip AND i EQUAL _skip)
    set(_after ON)
  endif()
endforeach()

if(CMAKE_HOST_WIN32)
  set(EZ "ez.cmd")
else()
  set(EZ "./ez")
endif()

set(B "${EZ_C_BOLD}")
set(D "${EZ_C_DIM}")
set(R "${EZ_C_RESET}")

# ---------------------------------------------------------------- presets, from CMake itself
function(_presets kind out)
  execute_process(COMMAND "${CMAKE_COMMAND}" --list-presets=${kind} WORKING_DIRECTORY "${EZ_ROOT}"
    OUTPUT_VARIABLE _raw ERROR_QUIET)
  string(REPLACE "\n" ";" _lines "${_raw}")
  set(_text "")
  foreach(_l IN LISTS _lines)
    if(_l MATCHES "^ *\"([^\"]+)\" *(- *(.*))?$")
      set(_name "${CMAKE_MATCH_1}")
      set(_desc "${CMAKE_MATCH_3}")
      string(REGEX REPLACE "^${_name}: *" "" _desc "${_desc}")
      string(LENGTH "${_name}" _n)
      math(EXPR _pad "10 - ${_n}")
      if(_pad LESS 1)
        set(_pad 1)
      endif()
      string(REPEAT " " ${_pad} _sp)
      string(APPEND _text "  ${_name}${_sp}${_desc}\n")
    endif()
  endforeach()
  set(${out} "${_text}" PARENT_SCOPE)
endfunction()

function(_preset_names kind out)
  execute_process(COMMAND "${CMAKE_COMMAND}" --list-presets=${kind} WORKING_DIRECTORY "${EZ_ROOT}"
    OUTPUT_VARIABLE _raw ERROR_QUIET)
  string(REGEX MATCHALL "\"[^\"]+\"" _names "${_raw}")
  string(REPLACE "\"" "" _names "${_names}")
  string(REPLACE ";" "  " _names "${_names}")
  set(${out} "${_names}" PARENT_SCOPE)
endfunction()

# ---------------------------------------------------------------- the overview
function(help_overview out)
  _preset_names(configure _cfg)
  set(_t "${B}eZeGo launcher${R}: short words for the canonical CMake commands. Every command prints the\ncommand it runs with ${D}${EZ} help <command>${R}; nothing here is required, CMake alone works.\n\n")
  string(APPEND _t "${B}Usage${R}\n  ${EZ} <command> [arguments]\n  ${EZ} help <command>        everything about one command (also: ${EZ} <command> --help)\n\n")
  string(APPEND _t "${B}Setup${R}\n")
  string(APPEND _t "  doctor                 check this machine and the repository; print the fix for each problem\n")
  string(APPEND _t "  init                   first-time setup: doctor, dependencies, tools, VS Code, configure debug\n")
  string(APPEND _t "  deps                   sync third_party/_src to dependencies.json (shallow, pinned, offline after)\n")
  string(APPEND _t "  tools                  install the pinned developer tools (Tracy)\n")
  string(APPEND _t "  vscode                 regenerate eZeGo.code-workspace with this machine's paths\n\n")
  string(APPEND _t "${B}Build and run${R}\n")
  string(APPEND _t "  build [preset]         configure and build one preset (default: debug)\n")
  string(APPEND _t "  run [preset] [-- app arguments]   build, then run the app from that tree\n")
  string(APPEND _t "  clean <preset>|all     delete build trees\n\n")
  string(APPEND _t "${B}Quality${R}\n")
  string(APPEND _t "  test [preset] [...]    build, then run that tree's tests (default: debug)\n")
  string(APPEND _t "  check                  the pre-merge gate: lint, clang-tidy, warnings as errors, every test\n")
  string(APPEND _t "  lint                   naming, layout, formatting and clang-tidy findings; --fix formats\n")
  string(APPEND _t "  bench                  micro-benchmarks from the release tree, with history\n")
  string(APPEND _t "  profile                build profile, open Tracy, run the app\n\n")
  string(APPEND _t "${B}Presets${R}   ${_cfg}        ${D}(${EZ} help build)${R}\n")
  string(APPEND _t "${B}Docs${R}      docs/getting-started.md  docs/build-modes.md  docs/testing.md  docs/lint.md  docs/profiling.md\n")
  set(${out} "${_t}" PARENT_SCOPE)
endfunction()

# ---------------------------------------------------------------- one command each
macro(_section title)
  string(APPEND _t "\n${B}${title}${R}\n")
endmacro()

function(help_doctor out)
  set(_t "${B}${EZ} doctor${R}: check this machine and the repository\n")
  _section("Usage")
  string(APPEND _t "  ${EZ} doctor\n")
  _section("What it checks")
  string(APPEND _t "  tools       CMake, Ninja, Clang, the linker, a compiler cache, clangd, clang-format, clang-tidy\n")
  string(APPEND _t "  system      the OS packages GLFW needs (Linux), the SDK (macOS), Build Tools (Windows)\n")
  string(APPEND _t "  repository  every dependency at its pinned commit, the dev tools, the build trees\n")
  string(APPEND _t "\nRead-only: it installs nothing. Each failed check prints the exact install command for\nthis OS. Exit code 1 if any check is an error.\n")
  _section("Runs")
  string(APPEND _t "  cmake -P scripts/doctor.cmake\n")
  set(${out} "${_t}" PARENT_SCOPE)
endfunction()

function(help_init out)
  set(_t "${B}${EZ} init${R}: first-time setup, safe to re-run\n")
  _section("Usage")
  string(APPEND _t "  ${EZ} init [--tools=prebuilt|source|skip] [--preset=<preset>] [--ignore-doctor]\n")
  _section("Steps, in order")
  string(APPEND _t "  1. doctor            stops here if something an error needs is missing\n")
  string(APPEND _t "  2. deps              fetch every dependency at its pinned commit\n")
  string(APPEND _t "  3. tools             install Tracy: a verified prebuilt (seconds) or built from source (a minute)\n")
  string(APPEND _t "  4. vscode            write eZeGo.code-workspace\n")
  string(APPEND _t "  5. configure debug   so VS Code and clangd work when the folder opens\n")
  _section("Options")
  string(APPEND _t "  --tools=prebuilt     download the verified prebuilt without asking\n")
  string(APPEND _t "  --tools=source       build the tools from the pinned source\n")
  string(APPEND _t "  --tools=skip         no tools (CI, or a machine that never profiles)\n")
  string(APPEND _t "  --preset=<preset>    configure this preset instead of debug\n")
  string(APPEND _t "  --ignore-doctor      continue past doctor's errors (you know what is missing)\n")
  _section("Runs")
  string(APPEND _t "  cmake -P scripts/init.cmake [--tools=...]\n")
  set(${out} "${_t}" PARENT_SCOPE)
endfunction()

function(help_deps out)
  set(_t "${B}${EZ} deps${R}: sync third_party/_src to dependencies.json\n")
  _section("Usage")
  string(APPEND _t "  ${EZ} deps [--check] [--only=<name>] [--force]\n")
  string(APPEND _t "\nEach dependency is a shallow git fetch of exactly its pinned commit, no history. Configure\nand build never touch the network; this is the one step that does.\n")
  _section("Options")
  string(APPEND _t "  --check              report what differs from the manifest; fetch nothing\n")
  string(APPEND _t "  --only=<name>        one dependency, e.g. --only=imgui\n")
  string(APPEND _t "  --force              re-fetch even if present, discarding local edits\n")
  _section("Runs")
  string(APPEND _t "  cmake -P scripts/deps.cmake [options]\n")
  set(${out} "${_t}" PARENT_SCOPE)
endfunction()

function(help_tools out)
  set(_t "${B}${EZ} tools${R}: install the pinned developer tools\n")
  _section("Usage")
  string(APPEND _t "  ${EZ} tools [--tools=prebuilt|source|skip] [--force]\n")
  string(APPEND _t "  ${EZ} tools --print=tracy:profiler      the path of one installed binary\n")
  string(APPEND _t "\nTools are pinned in dependencies.json like libraries, installed per user under the dev cache,\nand recorded with a provenance file so doctor can tell a stale one.\n")
  _section("Options")
  string(APPEND _t "  --tools=prebuilt|source|skip   how to install; without it, a terminal is asked\n")
  string(APPEND _t "  --force              reinstall even if the installed copy matches the pin\n")
  string(APPEND _t "  --print=<tool>:<binary>   print a binary's path: tracy:profiler, tracy:capture, tracy:csvexport\n")
  _section("Runs")
  string(APPEND _t "  cmake -P scripts/tools.cmake [options]\n")
  set(${out} "${_t}" PARENT_SCOPE)
endfunction()

function(help_vscode out)
  set(_t "${B}${EZ} vscode${R}: regenerate eZeGo.code-workspace\n")
  _section("Usage")
  string(APPEND _t "  ${EZ} vscode\n")
  string(APPEND _t "\nThe workspace file holds this machine's paths (Tracy, clangd); it is generated and git-ignored.\nOpening the plain folder works without it; the workspace adds the machine-specific tasks.\n")
  _section("Runs")
  string(APPEND _t "  cmake -P scripts/vscode.cmake\n")
  set(${out} "${_t}" PARENT_SCOPE)
endfunction()

function(help_build out)
  _presets(configure _p)
  set(_t "${B}${EZ} build${R}: configure and build one preset\n")
  _section("Usage")
  string(APPEND _t "  ${EZ} build [preset] [cmake build options]\n")
  string(APPEND _t "\nA preset is a build mode with its own tree, build/<preset>/. Switching presets never needs a\nclean; a tree that is already built rebuilds nothing. clangd follows the preset configured last.\n")
  _section("Presets (cmake --list-presets=configure)")
  string(APPEND _t "${_p}")
  _section("Options (cmake --build's; the useful ones)")
  string(APPEND _t "  --target <name>      one target, e.g. --target ez_test_log\n")
  string(APPEND _t "  --clean-first        rebuild everything in the tree\n")
  string(APPEND _t "  -v                   print every compiler command\n")
  _section("Examples")
  string(APPEND _t "  ${EZ} build                     debug\n")
  string(APPEND _t "  ${EZ} build release\n")
  string(APPEND _t "  ${EZ} build debug --target ezego\n")
  _section("Runs")
  string(APPEND _t "  cmake --workflow --preset <preset>              (configure + build)\n")
  string(APPEND _t "  cmake --build --preset <preset> [options]       (when options are given)\n")
  set(${out} "${_t}" PARENT_SCOPE)
endfunction()

function(help_run out)
  _preset_names(configure _names)
  set(_t "${B}${EZ} run${R}: build, then run the app\n")
  _section("Usage")
  string(APPEND _t "  ${EZ} run [preset] [-- <app arguments>]\n")
  string(APPEND _t "\nEverything after -- goes to the app. The app's own options are its runtime variables:\n${D}${EZ} run -- --help${R} lists every one with its default, range and meaning.\n")
  _section("Presets")
  string(APPEND _t "  ${_names}\n")
  _section("Examples")
  string(APPEND _t "  ${EZ} run                                debug\n")
  string(APPEND _t "  ${EZ} run release\n")
  string(APPEND _t "  ${EZ} run -- --log=all:debug             every log line\n")
  string(APPEND _t "  ${EZ} run -- --log.file                  also write a session log file\n")
  string(APPEND _t "  ${EZ} run -- --app.quit_after_s=5        close by itself after 5 seconds\n")
  string(APPEND _t "  ${EZ} run -- --help                      the app's options\n")
  _section("Runs")
  string(APPEND _t "  cmake -P scripts/run.cmake --preset=<preset> -- <app arguments>\n")
  set(${out} "${_t}" PARENT_SCOPE)
endfunction()

function(help_clean out)
  _preset_names(configure _names)
  set(_t "${B}${EZ} clean${R}: delete build trees\n")
  _section("Usage")
  string(APPEND _t "  ${EZ} clean <preset>       delete build/<preset>/\n")
  string(APPEND _t "  ${EZ} clean all            delete every tree under build/\n")
  string(APPEND _t "\nNormally unnecessary: presets have their own trees and never need a clean to switch. Use it\nwhen a tree was configured with a compiler that no longer exists (doctor says so) or to\nreclaim disk.\n")
  _section("Presets")
  string(APPEND _t "  ${_names}\n")
  _section("Runs")
  string(APPEND _t "  cmake -E rm -rf build/<preset>\n")
  set(${out} "${_t}" PARENT_SCOPE)
endfunction()

function(help_test out)
  _presets(test _p)
  set(_t "${B}${EZ} test${R}: build, then run the tests of one tree\n")
  _section("Usage")
  string(APPEND _t "  ${EZ} test [preset] [ctest options]\n")
  string(APPEND _t "\nThe preset names the tree; debug is the default and may be omitted even when options follow.\nEach doctest case is its own CTest test, so filters work per case and VS Code lists them.\nThe default run is unit + integration + smoke: headless, no device, under 30 s.\n")
  _section("Presets (ctest --list-presets=test)")
  string(APPEND _t "${_p}")
  _section("Labels")
  string(APPEND _t "  unit           one module, headless, under 1 s per case\n")
  string(APPEND _t "  integration    a few modules, headless, under 10 s per case\n")
  string(APPEND _t "  smoke          the real binary starts and answers --version\n")
  string(APPEND _t "  lint           layout and format checks (the check tree only)\n")
  string(APPEND _t "  gpu            needs a display and a GPU; runs only through the gpu preset\n")
  _section("Options (ctest's; the useful ones)")
  string(APPEND _t "  -L <label>               only cases with this label\n")
  string(APPEND _t "  -R <regex>               only cases whose name matches, e.g. -R \"log:\"\n")
  string(APPEND _t "  -E <regex>               exclude cases whose name matches\n")
  string(APPEND _t "  -N                       list the cases, run nothing\n")
  string(APPEND _t "  -j <n>                   run n cases at once\n")
  string(APPEND _t "  --rerun-failed           only what failed last time\n")
  string(APPEND _t "  --repeat until-fail:<n>  run each case n times; hunts a flaky one\n")
  string(APPEND _t "  -V                       show every case's output, not only failures\n")
  _section("Examples")
  string(APPEND _t "  ${EZ} test                          debug: unit + integration + smoke\n")
  string(APPEND _t "  ${EZ} test release                  the same in the release tree\n")
  string(APPEND _t "  ${EZ} test -L unit                  the preset may be omitted\n")
  string(APPEND _t "  ${EZ} test debug -R \"cvars:\"        one module's cases\n")
  string(APPEND _t "  ${EZ} test asan                     under Address and UB sanitizers\n")
  string(APPEND _t "  ${EZ} test gpu                      the GUI smoke test: opens a window\n")
  _section("Runs")
  string(APPEND _t "  cmake --workflow --preset <tree>  &&  ctest --preset <preset> [options]\n")
  set(${out} "${_t}" PARENT_SCOPE)
endfunction()

function(help_check out)
  set(_t "${B}${EZ} check${R}: the pre-merge gate\n")
  _section("Usage")
  string(APPEND _t "  ${EZ} check\n")
  string(APPEND _t "\nBuilds the check tree (build/check): debug, with clang-tidy running on every file and warnings\nas errors. Then runs lint as a test, and every test in random order. Nothing merges with a\nfinding. Locally the same findings are warnings in the editor and in a plain build.\n")
  _section("When it fails")
  string(APPEND _t "  a naming or layout finding    ${EZ} lint prints it with file and line; ${EZ} lint --fix formats\n")
  string(APPEND _t "  a compiler warning            it is an error here; fix it or justify a NOLINT with a reason\n")
  string(APPEND _t "  a test                        ${EZ} test check -R \"<name>\" --output-on-failure\n")
  _section("Runs")
  string(APPEND _t "  cmake --workflow --preset check\n")
  set(${out} "${_t}" PARENT_SCOPE)
endfunction()

function(help_lint out)
  set(_t "${B}${EZ} lint${R}: naming, layout, formatting and clang-tidy findings\n")
  _section("Usage")
  string(APPEND _t "  ${EZ} lint [--fix] [--tidy=off] [--format=off] [--preset=<preset>]\n")
  string(APPEND _t "\nFindings print as path:line: error: message [rule], which editors make clickable. The rules\nare specs/naming.md; the how-to is docs/lint.md.\n")
  _section("Options")
  string(APPEND _t "  --fix                apply clang-format to every first-party file instead of reporting\n")
  string(APPEND _t "  --tidy=off           skip clang-tidy (the layout and format checks take well under a second)\n")
  string(APPEND _t "  --format=off         skip the clang-format check\n")
  string(APPEND _t "  --preset=<preset>    the compile database clang-tidy uses (default: the tree configured last)\n")
  _section("Suppressing one finding")
  string(APPEND _t "  // NOLINT(ez-rule) reason           on the line, only for a name a third-party API dictates\n")
  _section("Runs")
  string(APPEND _t "  cmake -P scripts/lint.cmake [options]\n")
  set(${out} "${_t}" PARENT_SCOPE)
endfunction()

function(help_bench out)
  set(_t "${B}${EZ} bench${R}: micro-benchmarks from the release tree\n")
  _section("Usage")
  string(APPEND _t "  ${EZ} bench [--filter=<text>] [--min-ms=<n>] [--no-build]\n")
  string(APPEND _t "\nBuilds release, runs every tests/bench/*_bench.cpp executable, prints min, median and p99 per\noperation and the change against this machine's previous run. Results append to\nbuild/bench/history.jsonl with the commit. There is no gate: numbers inform, nothing fails.\n")
  _section("Options")
  string(APPEND _t "  --filter=<text>      only benchmarks whose name contains the text, e.g. --filter=log\n")
  string(APPEND _t "  --min-ms=<n>         sampling time per benchmark (default 300); more is steadier\n")
  string(APPEND _t "  --no-build           run what is built\n")
  _section("Runs")
  string(APPEND _t "  cmake -P scripts/bench.cmake [options]\n")
  set(${out} "${_t}" PARENT_SCOPE)
endfunction()

function(help_profile out)
  set(_t "${B}${EZ} profile${R}: a profiling session\n")
  _section("Usage")
  string(APPEND _t "  ${EZ} profile [-- <app arguments>]                    build profile, open Tracy, run the app\n")
  string(APPEND _t "  ${EZ} profile --capture=<file.tracy> [--seconds=<n>]   headless: record for n seconds (default 10)\n")
  string(APPEND _t "  ${EZ} profile --gui-only                              only open Tracy (VS Code's pre-launch task)\n")
  string(APPEND _t "\nThe profile preset is release code generation plus Tracy; the app records only while a viewer is\nconnected. Tracy is installed on first use if it is missing. Personal settings (a remote address,\na port) go in scripts/profile.user.cmake, which is git-ignored.\n")
  _section("Examples")
  string(APPEND _t "  ${EZ} profile\n")
  string(APPEND _t "  ${EZ} profile --capture=run.tracy --seconds=5\n")
  string(APPEND _t "  ${EZ} profile -- --log=all:debug\n")
  _section("Runs")
  string(APPEND _t "  cmake -P scripts/profile.cmake [options] [-- <app arguments>]\n")
  set(${out} "${_t}" PARENT_SCOPE)
endfunction()

function(help_help out)
  set(_t "${B}${EZ} help${R}: this launcher's help\n")
  _section("Usage")
  string(APPEND _t "  ${EZ} help                 the overview\n")
  string(APPEND _t "  ${EZ} help <command>       everything about one command\n")
  string(APPEND _t "  ${EZ} <command> --help     the same\n")
  _section("Runs")
  string(APPEND _t "  cmake -P scripts/help.cmake [command]\n")
  set(${out} "${_t}" PARENT_SCOPE)
endfunction()

# ---------------------------------------------------------------- dispatch
set(_commands doctor init deps tools vscode build run clean test check lint bench profile help)
if(_topic STREQUAL "")
  help_overview(_text)
elseif(_topic IN_LIST _commands)
  cmake_language(CALL help_${_topic} _text)
else()
  string(REPLACE ";" ", " _list "${_commands}")
  set(_text "${EZ_C_RED}unknown command '${_topic}'${R}\ncommands: ${_list}\n")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "${_text}")
  message(FATAL_ERROR "")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "${_text}")
