# Lint: the naming and layout rules that clang-tidy cannot see, plus formatting and clang-tidy.
# Read-only unless --fix is given. Exit code 1 if anything is wrong. (naming.md N-13)
#
#   cmake -P scripts/lint.cmake                 everything
#   cmake -P scripts/lint.cmake --tidy=off      skip clang-tidy (the check preset runs it in the build)
#   cmake -P scripts/lint.cmake --format=off    skip the clang-format check
#   cmake -P scripts/lint.cmake --fix           apply clang-format instead of reporting it
#   cmake -P scripts/lint.cmake --preset=debug  compile database for clang-tidy (default: build/)
#
# Findings print as `path:line: error: message [ez-rule]`, which editors make clickable.
# Suppress one finding on its line with `// NOLINT(ez-rule)` and a reason; suppressions are counted.
#
# Scope: first-party code in src/ez/, src/apps/, src/tools/, tests/, sdk/ and plugins/.

include("${CMAKE_CURRENT_LIST_DIR}/lib/common.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/lib/llvm.cmake")
ez_parse_args()

set(_errors 0)
set(_nolint 0)
set(_files_checked 0)

# ------------------------------------------------------------------ helpers
function(_finding file line rule msg)
  file(RELATIVE_PATH _rel "${EZ_ROOT}" "${file}")
  message("${_rel}:${line}: ${EZ_C_RED}error${EZ_C_RESET}: ${msg} [ez-${rule}]")
  math(EXPR _n "${_errors} + 1")
  set(_errors ${_n} PARENT_SCOPE)
endfunction()

# Split a file into a list of lines that survives `;`, `[`, `]` and empty lines.
function(_read_lines file out)
  file(READ "${file}" _c)
  string(ASCII 1 _semi)
  string(ASCII 2 _lb)
  string(ASCII 3 _rb)
  string(REPLACE "\r" "" _c "${_c}")
  string(REPLACE ";" "${_semi}" _c "${_c}")
  string(REPLACE "[" "${_lb}" _c "${_c}")
  string(REPLACE "]" "${_rb}" _c "${_c}")
  string(REPLACE "\n" ";" _c "${_c}")
  set(${out} "${_c}" PARENT_SCOPE)
endfunction()

function(_unescape in out)
  string(ASCII 1 _semi)
  string(ASCII 2 _lb)
  string(ASCII 3 _rb)
  string(REPLACE "${_semi}" ";" _s "${in}")
  string(REPLACE "${_lb}" "[" _s "${_s}")
  string(REPLACE "${_rb}" "]" _s "${_s}")
  set(${out} "${_s}" PARENT_SCOPE)
endfunction()

# ------------------------------------------------------------------ the module table (CO-8)
set(_modules "")
set(_table "${EZ_ROOT}/modules.cmake")
if(EXISTS "${_table}")
  function(ez_declare_module name layer deps description)
    set(_modules ${_modules} ${name} PARENT_SCOPE)
  endfunction()
  include("${_table}")
endif()

# ------------------------------------------------------------------ collect files
set(_scope_dirs src/ez src/apps src/tools tests sdk plugins)
set(_files "")
foreach(_d IN LISTS _scope_dirs)
  if(IS_DIRECTORY "${EZ_ROOT}/${_d}")
    file(GLOB_RECURSE _f LIST_DIRECTORIES false "${EZ_ROOT}/${_d}/*")
    list(APPEND _files ${_f})
  endif()
endforeach()
list(FILTER _files EXCLUDE REGEX "/tests/fuzz/corpus/|/tests/scenarios/")
list(SORT _files)

set(_sources "")
foreach(_f IN LISTS _files)
  get_filename_component(_name "${_f}" NAME)
  if(_name MATCHES "^(CMakeLists\\.txt|\\.clang-tidy|\\.clang-format|.*\\.cmake|.*\\.md)$")
    continue()
  endif()
  # N-8: lower_snake_case, ASCII, known extensions; generated files never committed.
  if(_name MATCHES "\\.(cc|cxx|hh|hxx|hpp\\+\\+|inl|ipp)$")
    _finding("${_f}" 1 file-extension "use .hpp for C++ headers, .h for C headers and .cpp for sources")
  elseif(_name MATCHES "\\.gen\\.(hpp|h)$")
    _finding("${_f}" 1 file-generated "generated files live only in build trees")
  elseif(_name MATCHES "\\.(hpp|h|cpp|c)$")
    if(NOT _name MATCHES "^[a-z0-9_]+\\.(hpp|h|cpp|c)$")
      _finding("${_f}" 1 file-name "file names are lower_snake_case: '${_name}'")
    endif()
    list(APPEND _sources "${_f}")
  endif()
endforeach()

# ------------------------------------------------------------------ module table and directories
if(_modules)
  file(GLOB _dirs LIST_DIRECTORIES true "${EZ_ROOT}/src/ez/*")
  foreach(_d IN LISTS _dirs)
    if(NOT IS_DIRECTORY "${_d}")
      continue()
    endif()
    get_filename_component(_m "${_d}" NAME)
    if(NOT _m IN_LIST _modules)
      _finding("${_d}" 1 module-table "src/ez/${_m}/ is not in modules.cmake; add it there or remove the directory")
    elseif(NOT EXISTS "${_d}/CMakeLists.txt")
      _finding("${_d}" 1 module-table "module '${_m}' has no CMakeLists.txt")
    endif()
  endforeach()
  foreach(_m IN LISTS _modules)
    if(NOT IS_DIRECTORY "${EZ_ROOT}/src/ez/${_m}")
      _finding("${_table}" 1 module-table "module '${_m}' is in the table but src/ez/${_m}/ does not exist")
    endif()
    if(NOT _m MATCHES "^[a-z][a-z0-9_]*$")
      _finding("${_table}" 1 module-table "module name '${_m}' must be one lower_snake_case word")
    endif()
  endforeach()
elseif(IS_DIRECTORY "${EZ_ROOT}/src/ez")
  _finding("${EZ_ROOT}/src/ez" 1 module-table "src/ez/ exists but modules.cmake does not")
endif()

# ------------------------------------------------------------------ per-file rules
foreach(_f IN LISTS _sources)
  math(EXPR _files_checked "${_files_checked} + 1")
  file(RELATIVE_PATH _rel "${EZ_ROOT}" "${_f}")
  get_filename_component(_ext "${_f}" LAST_EXT)

  # Which module owns this file, and which namespace must it use (N-2, CO-9)?
  set(_module "")
  set(_expected_ns "")
  if(_rel MATCHES "^src/ez/([a-z0-9_]+)/(.*)$")
    set(_module "${CMAKE_MATCH_1}")
    get_filename_component(_sub "${CMAKE_MATCH_2}" DIRECTORY)
    if(_module STREQUAL "base")
      set(_expected_ns "ez")
    else()
      set(_expected_ns "ez::${_module}")
    endif()
    if(_sub)
      string(REPLACE "/" "::" _sub_ns "${_sub}")
      set(_expected_ns "${_expected_ns}::${_sub_ns}")
    endif()
  elseif(_rel MATCHES "^tests/([a-z0-9_]+)/")
    set(_module "${CMAKE_MATCH_1}")   # tests of module m may use m's detail
  endif()

  _read_lines("${_f}" _lines)
  set(_ln 0)
  set(_seen_code OFF)
  set(_in_block_comment OFF)
  foreach(_raw IN LISTS _lines)
    math(EXPR _ln "${_ln} + 1")
    _unescape("${_raw}" _line)

    # Per-line suppression: // NOLINT(ez-rule)
    set(_suppressed "")
    if(_line MATCHES "NOLINT\\(([^)]*)\\)")
      set(_suppressed "${CMAKE_MATCH_1}")
    endif()
    macro(_report rule msg)
      if(_suppressed MATCHES "ez-${rule}")
        math(EXPR _nolint "${_nolint} + 1")
      else()
        _finding("${_f}" ${_ln} ${rule} "${msg}")
      endif()
    endmacro()

    # Strip line comments and string literals for the code rules below.
    string(REGEX REPLACE "\"([^\"\\\\]|\\\\.)*\"" "\"\"" _code "${_line}")
    string(REGEX REPLACE "//.*$" "" _code "${_code}")
    if(_in_block_comment)
      if(_code MATCHES "\\*/")
        set(_in_block_comment OFF)
        string(REGEX REPLACE "^.*\\*/" "" _code "${_code}")
      else()
        continue()
      endif()
    endif()
    if(_code MATCHES "/\\*" AND NOT _code MATCHES "/\\*.*\\*/")
      set(_in_block_comment ON)
      string(REGEX REPLACE "/\\*.*$" "" _code "${_code}")
    endif()
    string(REGEX REPLACE "/\\*.*\\*/" "" _code "${_code}")
    string(STRIP "${_code}" _code_s)

    # N-8: #pragma once is the first non-comment line of every header.
    if(NOT _seen_code AND NOT _code_s STREQUAL "")
      set(_seen_code ON)
      if(_ext MATCHES "^\\.(hpp|h)$" AND NOT _code_s STREQUAL "#pragma once")
        _report(pragma-once "headers start with #pragma once")
      endif()
    endif()

    # N-8: quoted includes are rooted (ez/, ezego/ for the SDK, support/ in tests), never relative.
    if(_line MATCHES "^[ \t]*#[ \t]*include[ \t]*\"([^\"]+)\"")
      set(_inc "${CMAKE_MATCH_1}")
      if(_inc MATCHES "\\.\\./|^\\./")
        _report(include-path "includes are rooted at src/, never relative: \"${_inc}\"")
      elseif(NOT _inc MATCHES "^(ez/|ezego/)" AND NOT (_rel MATCHES "^tests/" AND EXISTS "${EZ_ROOT}/tests/${_inc}"))
        _report(include-path "first-party includes start with ez/ (or ezego/; tests may include files under tests/ by their path there); third-party uses <>: \"${_inc}\"")
      endif()
      # CO-3: another module's detail/ is private.
      if(_inc MATCHES "^ez/([a-z0-9_]+)/detail/" AND NOT CMAKE_MATCH_1 STREQUAL _module)
        _report(detail-private "ez/${CMAKE_MATCH_1}/detail/ is private to module '${CMAKE_MATCH_1}'")
      endif()
    endif()
    if(_code MATCHES "ez::([a-z0-9_]+)::detail::" AND NOT CMAKE_MATCH_1 STREQUAL _module
       AND CMAKE_MATCH_1 IN_LIST _modules)
      _report(detail-private "ez::${CMAKE_MATCH_1}::detail is private to module '${CMAKE_MATCH_1}'")
    endif()

    # N-2: named namespaces are written in full and match the directory.
    if(_code MATCHES "^(inline[ \t]+)?namespace[ \t]+([A-Za-z0-9_:]+)[ \t]*(\\{|$)")
      set(_ns "${CMAKE_MATCH_2}")
      if(_ns STREQUAL "std")
        # specializations of std templates are allowed
      elseif(_expected_ns)
        if(_expected_ns MATCHES "::detail$")
          set(_allowed "${_expected_ns}")
          set(_allowed_text "'${_expected_ns}'")
        else()
          set(_allowed "${_expected_ns};${_expected_ns}::detail")
          set(_allowed_text "'${_expected_ns}' or '${_expected_ns}::detail'")
        endif()
        if(NOT _ns IN_LIST _allowed)
          _report(namespace "namespace '${_ns}' in this directory must be ${_allowed_text}; write the full path")
        endif()
      elseif(_rel MATCHES "^tests/" AND NOT _ns MATCHES "^ez(::|$)")
        _report(namespace "tests use an anonymous namespace or ez::...: '${_ns}'")
      endif()
      string(REGEX MATCHALL "::" _seps "${_ns}")
      list(LENGTH _seps _depth)
      if(_depth GREATER 3)
        _report(namespace "namespace '${_ns}' is deeper than ez::module::sub::detail")
      endif()
    elseif(_code MATCHES "^namespace[ \t]*\\{" AND _ext MATCHES "^\\.(hpp|h)$")
      _report(namespace "anonymous namespaces belong in .cpp files; use ${_expected_ns}::detail in headers")
    endif()

    # N-4: acronyms are written as words in type names (DmxFrame, not DMXFrame).
    if(_code MATCHES "(^|[^A-Za-z0-9_])(struct|class|union|enum|using|concept)[ \t]+([A-Z][A-Za-z0-9_]*)")
      set(_type "${CMAKE_MATCH_3}")
      if(_type MATCHES "[A-Z][A-Z][A-Z]" AND NOT _type MATCHES "^[A-Z0-9_]+$")
        _report(acronym "write acronyms as words in type names: '${_type}'")
      endif()
    endif()

    # N-6: thread_local variables carry the t_ prefix.
    if(_code MATCHES "thread_local[ \t]+[^;=({]*[^A-Za-z0-9_]([A-Za-z_][A-Za-z0-9_]*)[ \t]*(=|\\{|;|\\()")
      set(_tl "${CMAKE_MATCH_1}")
      if(NOT _tl MATCHES "^t_")
        _report(thread-local "thread_local variables start with t_: '${_tl}'")
      endif()
    endif()

    # N-6, N-9: cvar objects start with cv_; cvar names follow the registry grammar and start
    # with a module from the table.
    if(NOT _line MATCHES "^[ \t]*//" AND _line MATCHES "EZ_CVAR_[A-Z0-9_]+\\([ \t]*([A-Za-z0-9_]+)[ \t]*,[ \t]*\"([^\"]*)\"")
      set(_var "${CMAKE_MATCH_1}")
      set(_cv "${CMAKE_MATCH_2}")
      if(NOT _var MATCHES "^cv_")
        _report(cvar-name "cvar objects start with cv_: '${_var}'")
      endif()
      string(LENGTH "${_cv}" _len)
      if(NOT _cv MATCHES "^[a-z0-9_]+(\\.[a-z0-9_]+)*$" OR _len GREATER 63)
        _report(registry-name "'${_cv}' must be dotted lower_snake_case segments, at most 63 characters")
      elseif(_modules)
        string(REGEX MATCH "^[a-z0-9_]+" _first "${_cv}")
        if(NOT _first IN_LIST _modules AND NOT _first STREQUAL "plugin")
          _report(registry-name "'${_cv}' must start with a module from modules.cmake")
        endif()
      endif()
    endif()
  endforeach()
endforeach()

# ------------------------------------------------------------------ formatting
ez_llvm_compiler_major(_cmajor)
if(EZ_HOST_OS STREQUAL "macos")
  set(_cmajor "")
endif()
if(NOT EZ_ARG_format STREQUAL "off" AND _sources)
  ez_find_llvm_tool(clang-format _fmt _fmt_major COMPILER_MAJOR "${_cmajor}")
  if(NOT _fmt)
    message("${EZ_C_YELLOW}warning${EZ_C_RESET}: clang-format not found; formatting not checked (run doctor)")
  elseif(EZ_ARG_fix)
    execute_process(COMMAND "${_fmt}" -i -style=file ${_sources} WORKING_DIRECTORY "${EZ_ROOT}")
    message("formatted ${_files_checked} file(s) with clang-format ${_fmt_major}")
  else()
    execute_process(COMMAND "${_fmt}" --dry-run -style=file ${_sources}
      WORKING_DIRECTORY "${EZ_ROOT}" ERROR_VARIABLE _fmt_out RESULT_VARIABLE _rc)
    string(REGEX MATCHALL "[^\n]*: warning: code should be clang-formatted[^\n]*" _fmt_hits "${_fmt_out}")
    set(_fmt_files "")
    foreach(_h IN LISTS _fmt_hits)
      if(_h MATCHES "^(.*):([0-9]+):[0-9]+: warning")
        set(_ff "${CMAKE_MATCH_1}")
        if(NOT _ff IN_LIST _fmt_files)
          list(APPEND _fmt_files "${_ff}")
          if(NOT IS_ABSOLUTE "${_ff}")
            set(_ff "${EZ_ROOT}/${_ff}")
          endif()
          _finding("${_ff}" ${CMAKE_MATCH_2} format "not clang-formatted (first difference here); run: ez lint --fix")
        endif()
      endif()
    endforeach()
  endif()
endif()

# ------------------------------------------------------------------ clang-tidy
if(NOT EZ_ARG_tidy STREQUAL "off" AND _sources)
  set(_db_dir "${EZ_ROOT}/build")
  if(EZ_ARG_preset)
    set(_db_dir "${EZ_ROOT}/build/${EZ_ARG_preset}")
  endif()
  ez_find_llvm_tool(clang-tidy _tidy _tidy_major COMPILER_MAJOR "${_cmajor}")
  if(NOT _tidy)
    message("${EZ_C_YELLOW}warning${EZ_C_RESET}: clang-tidy not found; naming rules not checked (run doctor)")
  elseif(NOT EXISTS "${_db_dir}/compile_commands.json")
    message("${EZ_C_YELLOW}warning${EZ_C_RESET}: no compile database in ${_db_dir}; build once, then re-run (clang-tidy skipped)")
  else()
    # Translation units only; headers are checked through them (HeaderFilterRegex in .clang-tidy).
    set(_tus "${_sources}")
    list(FILTER _tus INCLUDE REGEX "\\.(cpp|c)$")
    file(READ "${_db_dir}/compile_commands.json" _db)
    set(_in_db "")
    foreach(_tu IN LISTS _tus)
      string(FIND "${_db}" "\"${_tu}\"" _pos)
      if(NOT _pos EQUAL -1)
        list(APPEND _in_db "${_tu}")
      endif()
    endforeach()
    if(_in_db)
      cmake_host_system_information(RESULT _jobs QUERY NUMBER_OF_LOGICAL_CORES)
      ez_find_llvm_tool(run-clang-tidy _runner _runner_major COMPILER_MAJOR "${_tidy_major}")
      if(_runner)
        string(REPLACE ";" "|" _rx "${_in_db}")
        execute_process(COMMAND "${_runner}" -quiet -clang-tidy-binary "${_tidy}" -p "${_db_dir}" -j ${_jobs} ${_in_db}
          WORKING_DIRECTORY "${EZ_ROOT}" OUTPUT_VARIABLE _tidy_out ERROR_QUIET)
      else()
        set(_tidy_out "")
        foreach(_tu IN LISTS _in_db)
          execute_process(COMMAND "${_tidy}" --quiet -p "${_db_dir}" "${_tu}"
            WORKING_DIRECTORY "${EZ_ROOT}" OUTPUT_VARIABLE _o ERROR_QUIET)
          string(APPEND _tidy_out "${_o}")
        endforeach()
      endif()
      string(REGEX MATCHALL "[^\n]*: (warning|error): [^\n]*\\[[a-z-]+[^\n]*\\]" _hits "${_tidy_out}")
      list(REMOVE_DUPLICATES _hits)
      foreach(_h IN LISTS _hits)
        message("${_h}")
        math(EXPR _errors "${_errors} + 1")
      endforeach()
    endif()
  endif()
endif()

# ------------------------------------------------------------------ summary
message("")
if(_errors GREATER 0)
  message("${EZ_C_RED}${_errors} finding(s)${EZ_C_RESET} in ${_files_checked} file(s); ${_nolint} suppressed with NOLINT")
  message(FATAL_ERROR "lint failed")
else()
  message("${EZ_C_GREEN}lint clean${EZ_C_RESET}: ${_files_checked} file(s); ${_nolint} suppressed with NOLINT")
endif()
