# Install the pinned development tools (B-14).
#
#   cmake -P scripts/tools.cmake [--tools=auto|prebuilt|source|skip] [--force] [--soft]
#   cmake -P scripts/tools.cmake --print=tracy:profiler      (prints a binary path, for launchers)
#
#   auto      (default) prebuilt if a verified one exists for this OS, else source.
#             When a terminal is attached and a prebuilt exists, you are asked.
#   prebuilt  download the upstream binary, verified against the SHA-256 in dependencies.json
#   source    build from the pinned source in third_party/_src/<dep>
#   skip      do nothing
#   --soft    failures are warnings (used by init: tools must never block building the app)
#
# Tools install per user, keyed by version: <cache>/tools/<name>-<version>/, each with a
# PROVENANCE.json saying where the binaries came from. Override the location with EZ_TOOLS_DIR.

include("${CMAKE_CURRENT_LIST_DIR}/lib/common.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/lib/tooling.cmake")
ez_parse_args()

if(NOT EZ_ARG_tools)
  set(EZ_ARG_tools auto)
endif()

# ------------------------------------------------------------------ --print=<tool>:<binary>
if(EZ_ARG_print)
  string(REPLACE ":" ";" _q "${EZ_ARG_print}")
  list(GET _q 0 _tool)
  list(GET _q 1 _bin)
  ez_tool_binary(${_tool} ${_bin} _path)
  if(NOT _path OR NOT EXISTS "${_path}")
    message(FATAL_ERROR "${_tool}:${_bin} is not installed. Run: cmake -P scripts/tools.cmake")
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "${_path}")
  return()
endif()

if(EZ_ARG_tools STREQUAL "skip")
  ez_step("Dev tools: skipped (--tools=skip)")
  return()
endif()

# ------------------------------------------------------------------ interactivity
function(ez_is_interactive out)
  set(_i OFF)
  if(NOT DEFINED ENV{CI} AND NOT DEFINED ENV{EZ_NONINTERACTIVE})
    if(CMAKE_HOST_WIN32)
      execute_process(COMMAND powershell -NoProfile -Command "[Console]::IsInputRedirected"
        OUTPUT_VARIABLE _r OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
      if(_r STREQUAL "False")
        set(_i ON)
      endif()
    else()
      execute_process(COMMAND sh -c "test -t 0 && test -r /dev/tty" RESULT_VARIABLE _r)
      if(_r EQUAL 0)
        set(_i ON)
      endif()
    endif()
  endif()
  set(${out} ${_i} PARENT_SCOPE)
endfunction()

function(ez_ask question default out)
  if(CMAKE_HOST_WIN32)
    execute_process(COMMAND powershell -NoProfile -Command "Read-Host '${question}'"
      OUTPUT_VARIABLE _a OUTPUT_STRIP_TRAILING_WHITESPACE)
  else()
    execute_process(COMMAND sh -c "printf '%s ' \"$1\" > /dev/tty; read a < /dev/tty; printf '%s' \"$a\"" sh "${question}"
      OUTPUT_VARIABLE _a OUTPUT_STRIP_TRAILING_WHITESPACE)
  endif()
  if(_a STREQUAL "")
    set(_a "${default}")
  endif()
  set(${out} "${_a}" PARENT_SCOPE)
endfunction()

# ------------------------------------------------------------------ verified download
# Downloads into the per-user cache and verifies SHA-256. On any problem `err` is set and the
# file is deleted: an unverified binary is never used.
function(ez_fetch_prebuilt url sha key out_archive out_err)
  ez_user_cache_root(cache)
  get_filename_component(fname "${url}" NAME)
  set(archive "${cache}/downloads/${key}-${fname}")
  set(${out_archive} "${archive}" PARENT_SCOPE)
  set(${out_err} "" PARENT_SCOPE)
  if(EXISTS "${archive}")
    file(SHA256 "${archive}" have)
    if(have STREQUAL sha)
      return()
    endif()
    file(REMOVE "${archive}")
  endif()
  message("  ...   downloading ${url}")
  file(DOWNLOAD "${url}" "${archive}" STATUS st TLS_VERIFY ON)
  list(GET st 0 code)
  if(NOT code EQUAL 0)
    file(REMOVE "${archive}")
    set(${out_err} "download failed: ${st}" PARENT_SCOPE)
    return()
  endif()
  file(SHA256 "${archive}" have)
  if(NOT have STREQUAL sha)
    file(REMOVE "${archive}")
    set(${out_err} "SHA-256 MISMATCH for ${url}: expected ${sha}, got ${have}. The file was deleted, not used." PARENT_SCOPE)
  endif()
endfunction()

# ------------------------------------------------------------------ install one tool
function(ez_install_tool recipe)
  include("${recipe}")   # function scope: recipe variables don't leak between tools
  set(dep ${TOOL_DEP})
  ez_manifest_get(${dep} version version)
  ez_manifest_get(${dep} commit commit)
  ez_manifest_get(${dep} prebuilt_url prebuilt ${EZ_HOST} url)
  ez_manifest_get(${dep} prebuilt_sha prebuilt ${EZ_HOST} sha256)
  ez_tools_root(root)
  set(install_dir "${root}/${dep}-${version}")
  string(SUBSTRING "${commit}" 0 10 short)

  ez_tool_state(${dep} state origin)
  if(state STREQUAL "OK" AND NOT EZ_ARG_force)
    ez_report(OK "${dep} ${version}" "${origin}; ${install_dir}")
    return()
  endif()

  # Decide prebuilt vs source.
  set(method "${EZ_ARG_tools}")
  set(auto_mode OFF)
  if(method STREQUAL "auto")
    set(auto_mode ON)
    if(prebuilt_url AND prebuilt_sha)
      ez_is_interactive(interactive)
      if(interactive)
        message("")
        message("  ${dep} ${version}: a verified prebuilt exists for ${EZ_HOST}.")
        message("    [p] download the upstream binary (seconds; SHA-256 checked)")
        message("    [s] build from the pinned source ${short} (minutes, once)")
        ez_ask("  choose [P/s]:" "p" answer)
        string(TOLOWER "${answer}" answer)
        if(answer MATCHES "^s")
          set(method source)
        else()
          set(method prebuilt)
        endif()
      else()
        set(method prebuilt)
      endif()
    else()
      message("  ${dep} ${version}: no prebuilt listed for ${EZ_HOST}; building from source")
      set(method source)
    endif()
  endif()
  if(method STREQUAL "prebuilt" AND NOT (prebuilt_url AND prebuilt_sha))
    message(FATAL_ERROR "${dep}: no prebuilt for ${EZ_HOST} in dependencies.json; use --tools=source")
  endif()

  file(REMOVE_RECURSE "${install_dir}")
  file(MAKE_DIRECTORY "${install_dir}")
  string(TIMESTAMP now "%Y-%m-%dT%H:%M:%SZ" UTC)

  if(method STREQUAL "prebuilt")
    ez_fetch_prebuilt("${prebuilt_url}" "${prebuilt_sha}" "${dep}-${version}-${EZ_HOST}" archive fetch_err)
    if(fetch_err AND auto_mode)
      # A mismatch or failed download counts as "no prebuilt": say so loudly, build instead.
      message("  ${EZ_C_YELLOW}warn ${EZ_C_RESET} ${dep}: prebuilt rejected: ${fetch_err}")
      message("         falling back to a source build of the pinned commit")
      set(method source)
    elseif(fetch_err)
      message(FATAL_ERROR "${dep}: ${fetch_err}\nBuild from source instead: cmake -P scripts/tools.cmake --tools=source")
    else()
      tool_install_prebuilt("${archive}" "${install_dir}")
      set(prov_origin prebuilt)
      set(prov_source "${prebuilt_url}")
      set(prov_hash "${prebuilt_sha}")
    endif()
  endif()
  if(method STREQUAL "source")
    set(src "${EZ_SRC_ROOT}/${dep}")
    ez_dep_is_current(${dep} current)
    if(NOT current)
      message("  ...   ${dep}  source not at the pin; fetching")
      execute_process(COMMAND "${CMAKE_COMMAND}" -P "${EZ_ROOT}/scripts/deps.cmake" --only=${dep} RESULT_VARIABLE rc)
      if(NOT rc EQUAL 0)
        message(FATAL_ERROR "${dep}: could not fetch the pinned source")
      endif()
    endif()
    ez_user_cache_root(cache)
    tool_build_source("${src}" "${cache}/tool-builds/${dep}-${version}" "${install_dir}")
    set(prov_origin source)
    set(prov_source "${commit}")
    set(prov_hash "")
  endif()

  # Verify the expected binaries exist, then write provenance (for humans; B-14).
  tool_binaries("${install_dir}" bins)
  set(bin_json "{}")
  foreach(pair IN LISTS bins)
    string(REPLACE "=" ";" kv "${pair}")
    list(GET kv 0 k)
    list(GET kv 1 v)
    if(NOT EXISTS "${v}")
      message(FATAL_ERROR "${dep}: expected binary missing after install: ${v}")
    endif()
    file(RELATIVE_PATH rel "${install_dir}" "${v}")
    string(JSON bin_json SET "${bin_json}" "${k}" "\"${rel}\"")
  endforeach()
  set(j "{}")
  string(JSON j SET "${j}" tool "\"${dep}\"")
  string(JSON j SET "${j}" version "\"${version}\"")
  string(JSON j SET "${j}" commit "\"${commit}\"")
  string(JSON j SET "${j}" origin "\"${prov_origin}\"")
  string(JSON j SET "${j}" source "\"${prov_source}\"")
  string(JSON j SET "${j}" sha256 "\"${prov_hash}\"")
  string(JSON j SET "${j}" host "\"${EZ_HOST}\"")
  string(JSON j SET "${j}" installed "\"${now}\"")
  string(JSON j SET "${j}" binaries "${bin_json}")
  file(WRITE "${install_dir}/PROVENANCE.json" "${j}\n")
  if(prov_origin STREQUAL "prebuilt")
    ez_report(OK "${dep} ${version}" "prebuilt, verified; ${install_dir}")
  else()
    ez_report(OK "${dep} ${version}" "built from source ${short}; ${install_dir}")
  endif()
endfunction()

# ------------------------------------------------------------------ main
set(EZ_REPORT_ERRORS 0)
set(EZ_REPORT_WARNINGS 0)
ez_tools_root(_root)
if(NOT DEFINED EZ_ONLY_RECIPE)
  ez_step("Dev tools -> ${_root}")
endif()
file(GLOB _recipes "${EZ_ROOT}/tools/*.cmake")
set(_failed "")
foreach(_r IN LISTS _recipes)
  get_filename_component(_name "${_r}" NAME_WE)
  if(EZ_ARG_soft)
    # Run each recipe in a child process so a failure stays a warning.
    set(_fwd "--tools=${EZ_ARG_tools}")
    if(EZ_ARG_force)
      list(APPEND _fwd --force)
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -DEZ_ONLY_RECIPE=${_name} -P "${CMAKE_CURRENT_LIST_FILE}" ${_fwd}
      RESULT_VARIABLE _rc)
    if(NOT _rc EQUAL 0)
      list(APPEND _failed ${_name})
    endif()
  elseif(NOT DEFINED EZ_ONLY_RECIPE OR EZ_ONLY_RECIPE STREQUAL _name)
    ez_install_tool("${_r}")
  endif()
endforeach()

if(_failed)
  message("  ${EZ_C_YELLOW}warn ${EZ_C_RESET} tool(s) not installed: ${_failed}. The app still builds; "
          "profiling needs them. Retry: cmake -P scripts/tools.cmake")
endif()
if(NOT DEFINED EZ_ONLY_RECIPE)
  ez_write_vscode_workspace()
endif()
