# Runs inside ctest (not at configure time): turns the doctest cases of one test executable into
# CTest tests. Included from <target>_include.cmake written by ez_test() in cmake/testing.cmake.
#
# The executable is asked for its cases once, as XML, and the result is cached next to it; a
# rebuilt executable is listed again. Each case runs as `<exe> --test-case=<exact name>`.

if(NOT EXISTS "${EZ_TEST_EXE}")
  add_test("${EZ_TEST_TARGET}: not built" "${EZ_TEST_EXE}")
  return()
endif()

if(NOT EXISTS "${EZ_TEST_LIST}" OR "${EZ_TEST_EXE}" IS_NEWER_THAN "${EZ_TEST_LIST}")
  execute_process(COMMAND "${EZ_TEST_EXE}" --list-test-cases --reporters=xml --no-version
    WORKING_DIRECTORY "${EZ_TEST_WORKDIR}" OUTPUT_VARIABLE _xml RESULT_VARIABLE _rc ERROR_VARIABLE _err)
  if(NOT _rc EQUAL 0)
    file(WRITE "${EZ_TEST_LIST}" "add_test([==[${EZ_TEST_TARGET}: listing failed]==] [==[${EZ_TEST_EXE}]==] --list-test-cases)\n")
  else()
    set(_out "# Generated by cmake/test_discovery.cmake from ${EZ_TEST_TARGET}. Do not edit.\n")
    string(REGEX MATCHALL "<TestCase [^>]*/>" _cases "${_xml}")
    foreach(_c IN LISTS _cases)
      string(REGEX MATCH " name=\"([^\"]*)\"" _ "${_c}")
      set(_name "${CMAKE_MATCH_1}")
      set(_suite "")
      if(_c MATCHES " testsuite=\"([^\"]*)\"")
        set(_suite "${CMAKE_MATCH_1}")
      endif()
      set(_skipped OFF)
      if(_c MATCHES " skipped=\"true\"")
        set(_skipped ON)
      endif()
      foreach(_pair "&quot;|\"" "&lt;|<" "&gt;|>" "&apos;|'" "&amp;|&")
        string(REPLACE "|" ";" _p "${_pair}")
        list(GET _p 0 _from)
        list(GET _p 1 _to)
        string(REPLACE "${_from}" "${_to}" _name "${_name}")
      endforeach()
      # doctest filters treat ',' as a separator; escape it so the filter matches exactly one case.
      string(REPLACE "," "\\," _filter "${_name}")
      set(_label "${EZ_TEST_LABEL}")
      if(_suite)
        set(_label "${_suite}")
      endif()
      if(DEFINED EZ_TEST_TIMEOUT_${_label})
        set(_timeout ${EZ_TEST_TIMEOUT_${_label}})
      else()
        set(_timeout ${EZ_TEST_TIMEOUT_default})
      endif()
      string(APPEND _out
        "add_test([==[${_name}]==] [==[${EZ_TEST_EXE}]==] [==[--test-case=${_filter}]==] --no-version)\n"
        "set_tests_properties([==[${_name}]==] PROPERTIES LABELS [==[${_label}]==] TIMEOUT ${_timeout}"
        " WORKING_DIRECTORY [==[${EZ_TEST_WORKDIR}]==] FAIL_REGULAR_EXPRESSION [==[test cases: *0 \\|]==]")
      if(_skipped)
        string(APPEND _out " DISABLED TRUE")
      endif()
      string(APPEND _out ")\n")
    endforeach()
    file(WRITE "${EZ_TEST_LIST}" "${_out}")
  endif()
endif()
include("${EZ_TEST_LIST}")
